export const allCountries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States of America",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const regionMap: { [key: string]: string } = {
    'Afghanistan': 'South Asia',
    'Albania': 'Europe',
    'Algeria': 'North Africa',
    'Andorra': 'Europe',
    'Angola': 'Sub-Saharan Africa',
    'Antigua and Barbuda': 'Caribbean',
    'Argentina': 'South America',
    'Armenia': 'Caucasus',
    'Australia': 'Oceania',
    'Austria': 'Europe',
    'Azerbaijan': 'Caucasus',
    'Bahamas': 'Caribbean',
    'Bahrain': 'Middle East',
    'Bangladesh': 'South Asia',
    'Barbados': 'Caribbean',
    'Belarus': 'Europe',
    'Belgium': 'Europe',
    'Belize': 'Central America',
    'Benin': 'Sub-Saharan Africa',
    'Bhutan': 'South Asia',
    'Bolivia': 'South America',
    'Bosnia and Herzegovina': 'Europe',
    'Botswana': 'Sub-Saharan Africa',
    'Brazil': 'South America',
    'Brunei': 'Southeast Asia',
    'Bulgaria': 'Europe',
    'Burkina Faso': 'Sub-Saharan Africa',
    'Burundi': 'Sub-Saharan Africa',
    'Cabo Verde': 'Sub-Saharan Africa',
    'Cambodia': 'Southeast Asia',
    'Cameroon': 'Sub-Saharan Africa',
    'Canada': 'North America',
    'Central African Republic': 'Sub-Saharan Africa',
    'Chad': 'Sub-Saharan Africa',
    'Chile': 'South America',
    'China': 'East Asia',
    'Colombia': 'South America',
    'Comoros': 'Sub-Saharan Africa',
    'Congo': 'Sub-Saharan Africa',
    'Costa Rica': 'Central America',
    'Croatia': 'Europe',
    'Cuba': 'Caribbean',
    'Cyprus': 'Europe',
    'Czech Republic': 'Europe',
    'Denmark': 'Europe',
    'Djibouti': 'Sub-Saharan Africa',
    'Dominica': 'Caribbean',
    'Dominican Republic': 'Caribbean',
    'East Timor': 'Southeast Asia',
    'Ecuador': 'South America',
    'Egypt': 'North Africa',
    'El Salvador': 'Central America',
    'Equatorial Guinea': 'Sub-Saharan Africa',
    'Eritrea': 'Sub-Saharan Africa',
    'Estonia': 'Europe',
    'Eswatini': 'Sub-Saharan Africa',
    'Ethiopia': 'Sub-Saharan Africa',
    'Fiji': 'Oceania',
    'Finland': 'Europe',
    'France': 'Europe',
    'Gabon': 'Sub-Saharan Africa',
    'Gambia': 'Sub-Saharan Africa',
    'Georgia': 'Caucasus',
    'Germany': 'Europe',
    'Ghana': 'Sub-Saharan Africa',
    'Greece': 'Europe',
    'Grenada': 'Caribbean',
    'Guatemala': 'Central America',
    'Guinea': 'Sub-Saharan Africa',
    'Guinea-Bissau': 'Sub-Saharan Africa',
    'Guyana': 'South America',
    'Haiti': 'Caribbean',
    'Honduras': 'Central America',
    'Hungary': 'Europe',
    'Iceland': 'Europe',
    'India': 'South Asia',
    'Indonesia': 'Southeast Asia',
    'Iran': 'Middle East',
    'Iraq': 'Middle East',
    'Ireland': 'Europe',
    'Israel': 'Middle East',
    'Italy': 'Europe',
    'Ivory Coast': 'Sub-Saharan Africa',
    'Jamaica': 'Caribbean',
    'Japan': 'East Asia',
    'Jordan': 'Middle East',
    'Kazakhstan': 'Central Asia',
    'Kenya': 'Sub-Saharan Africa',
    'Kiribati': 'Oceania',
    'Kosovo': 'Europe',
    'Kuwait': 'Middle East',
    'Kyrgyzstan': 'Central Asia',
    'Laos': 'Southeast Asia',
    'Latvia': 'Europe',
    'Lebanon': 'Middle East',
    'Lesotho': 'Sub-Saharan Africa',
    'Liberia': 'Sub-Saharan Africa',
    'Libya': 'North Africa',
    'Liechtenstein': 'Europe',
    'Lithuania': 'Europe',
    'Luxembourg': 'Europe',
    'Madagascar': 'Sub-Saharan Africa',
    'Malawi': 'Sub-Saharan Africa',
    'Malaysia': 'Southeast Asia',
    'Maldives': 'South Asia',
    'Mali': 'Sub-Saharan Africa',
    'Malta': 'Europe',
    'Marshall Islands': 'Oceania',
    'Mauritania': 'Sub-Saharan Africa',
    'Mauritius': 'Sub-Saharan Africa',
    'Mexico': 'North America',
    'Micronesia': 'Oceania',
    'Moldova': 'Europe',
    'Monaco': 'Europe',
    'Mongolia': 'East Asia',
    'Montenegro': 'Europe',
    'Morocco': 'North Africa',
    'Mozambique': 'Sub-Saharan Africa',
    'Myanmar': 'Southeast Asia',
    'Namibia': 'Sub-Saharan Africa',
    'Nauru': 'Oceania',
    'Nepal': 'South Asia',
    'Netherlands': 'Europe',
    'New Zealand': 'Oceania',
    'Nicaragua': 'Central America',
    'Niger': 'Sub-Saharan Africa',
    'Nigeria': 'Sub-Saharan Africa',
    'North Korea': 'East Asia',
    'North Macedonia': 'Europe',
    'Norway': 'Europe',
    'Oman': 'Middle East',
    'Pakistan': 'South Asia',
    'Palau': 'Oceania',
    'Palestine': 'Middle East',
    'Panama': 'Central America',
    'Papua New Guinea': 'Oceania',
    'Paraguay': 'South America',
    'Peru': 'South America',
    'Philippines': 'Southeast Asia',
    'Poland': 'Europe',
    'Portugal': 'Europe',
    'Qatar': 'Middle East',
    'Romania': 'Europe',
    'Russia': 'Europe',
    'Rwanda': 'Sub-Saharan Africa',
    'Saint Kitts and Nevis': 'Caribbean',
    'Saint Lucia': 'Caribbean',
    'Saint Vincent and the Grenadines': 'Caribbean',
    'Samoa': 'Oceania',
    'San Marino': 'Europe',
    'Sao Tome and Principe': 'Sub-Saharan Africa',
    'Saudi Arabia': 'Middle East',
    'Senegal': 'Sub-Saharan Africa',
    'Serbia': 'Europe',
    'Seychelles': 'Sub-Saharan Africa',
    'Sierra Leone': 'Sub-Saharan Africa',
    'Singapore': 'Southeast Asia',
    'Slovakia': 'Europe',
    'Slovenia': 'Europe',
    'Solomon Islands': 'Oceania',
    'Somalia': 'Sub-Saharan Africa',
    'South Africa': 'Sub-Saharan Africa',
    'South Korea': 'East Asia',
    'South Sudan': 'Sub-Saharan Africa',
    'Spain': 'Europe',
    'Sri Lanka': 'South Asia',
    'Sudan': 'Sub-Saharan Africa',
    'Suriname': 'South America',
    'Sweden': 'Europe',
    'Switzerland': 'Europe',
    'Syria': 'Middle East',
    'Taiwan': 'East Asia',
    'Tajikistan': 'Central Asia',
    'Tanzania': 'Sub-Saharan Africa',
    'Thailand': 'Southeast Asia',
    'Togo': 'Sub-Saharan Africa',
    'Tonga': 'Oceania',
    'Trinidad and Tobago': 'Caribbean',
    'Tunisia': 'North Africa',
    'Turkey': 'Middle East',
    'Turkmenistan': 'Central Asia',
    'Tuvalu': 'Oceania',
    'Uganda': 'Sub-Saharan Africa',
    'Ukraine': 'Europe',
    'United Arab Emirates': 'Middle East',
    'United Kingdom': 'Europe',
    'United States of America': 'North America',
    'Uruguay': 'South America',
    'Uzbekistan': 'Central Asia',
    'Vanuatu': 'Oceania',
    'Vatican City': 'Europe',
    'Venezuela': 'South America',
    'Vietnam': 'Southeast Asia',
    'Yemen': 'Middle East',
    'Zambia': 'Sub-Saharan Africa',
    'Zimbabwe': 'Sub-Saharan Africa'
};

export const sectors = [
    "Aerospace & defence",
    "Automotive",
    "Construction",
    "Energy",
    "Environment",
    "Financial services",
    "Food & agriculture",
    "Government",
    "Healthcare",
    "Information Technology",
    "Manufacturing",
    "Media & entertainment",
    "Retail",
    "Security",
    "Support services",
    "Tourism & hospitality",
    "Transport",
    "Water"
]